[package]
name = "server_test"
version = "0.1.0"
authors = ["zhaoye-ds1 <zhaoye-ds1@gomeplus.com>"]

[dependencies]
gotham = "0.2.0"
gotham_derive = "*"
bson = "0.10.0"
mongodb = "0.3.7"
futures = "*"
mime = "*"
hyper = "*"